### ISSUE TITLE
Gjøremål

### ISSUE THREAD

**Issue by SiMENhol** [xBroccoliMaster69x/GRUPPE-REPOSITORY#102]
Gjøre UiA bilde til en link der du kommer tilbake
Fikse visualiser siden
Endre i hwr fra 2 til 11 på json

**Comment by SiMENhol** [comment]
"Endre i hwr fra 2 til 11 på json" er fikset opp i

**Comment by ToBeAss** [comment]
Gjort både UiA logo og sidetittelen funksjonell :)

**Comment by ToBeAss** [comment]
Issue er ferdig
